










 88%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰         | 43/49 [00:19<00:02,  2.60it/s]
[32m[2023-03-14 22:10:27 resnet18][33m(main.py 182)[39m: INFO Train: [0/100]	lr 0.000300	time 0.3248 (0.4392)	loss 1.2297 (1.5984)	Acc@1 54.127 (41.890)	Mem 5250MB
[32m[2023-03-14 22:10:27 resnet18][33m(main.py 191)[39m: INFO EPOCH 0 training takes 0:00:21
[32m[2023-03-14 22:10:27 resnet18][33m(main.py 117)[39m: INFO  * Train Acc 41.890 Train Loss 1.598
[32m[2023-03-14 22:10:27 resnet18][33m(main.py 118)[39m: INFO Accuracy of the network on the 50000 train images: 41.9%
Traceback (most recent call last):
  File "/home/narisam/sp23-nmep-hw1/main.py", line 289, in <module>
    main(config)
  File "/home/narisam/sp23-nmep-hw1/main.py", line 132, in main
    log_stats = {"epoch": epoch, "n_params": n_parameters, "n_flops": n_flops,
NameError: name 'n_flops' is not defined
[32m[2023-03-14 22:10:29 resnet18][33m(main.py 224)[39m: INFO Validate: 	Time 0.086 (0.181)	Loss 1.2624 (1.2435)	Acc@1 53.954 (55.320)	Mem 5250MB
[32m[2023-03-14 22:10:29 resnet18][33m(main.py 122)[39m: INFO  * Val Acc 55.320 Val Loss 1.244
[32m[2023-03-14 22:10:29 resnet18][33m(main.py 123)[39m: INFO Accuracy of the network on the 10000 val images: 55.3%
[32m[2023-03-14 22:10:29 resnet18][33m(load_save.py 48)[39m: INFO output/resnet18/ckpt_best.pth saving......
[32m[2023-03-14 22:10:29 resnet18][33m(load_save.py 50)[39m: INFO output/resnet18/ckpt_best.pth saved !!!
[32m[2023-03-14 22:10:29 resnet18][33m(main.py 129)[39m: INFO Max accuracy: 55.32%